  GNU nano 5.4                                              docker-compose.yml                                                       
version: "3.3"
services:
  database:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - mired2
  servidor:
    build: ./servidor
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: on-failure
    networks:
      - mired
      - mired2

  interprete:
    image: alpine
    stdin_open: true
    tty: true
    networks:
      - mired
volumes:
  my-datavolume:
    external: true

networks:
  mired:
    name: mired
    external: true
  mired2:
    name: mired2
    external: true
