version: "3.3"
services:
  database:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
  servidor:
    build: ./servidor
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
    ports:
      - "5000:5000"
    depends_on:
      - database
    restart: on-failure
  interprete:
    image: alpine
    stdin_open: true
    tty: true
volumes:
  my-datavolume:
    external: true
